apiVersion: v1
kind: Pod
metadata:
  name: sassational-pod
spec:
  containers:
    - name: sassational-container
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: sassational-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: sassational-secret
              key: password
