apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: lento
  name: sassational-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /mnt/data
  storageClassName: sassational-sc
