apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: sassational-pvc
  name: sassational-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sassational-sc
