apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: sassational-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sassational-nginx
  template:
    metadata:
      labels:
        app: sassational-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http

