apiVersion: v1
kind: Service
metadata:
  name: sassational-nginx
  labels:
    app: sassational-nginx
spec:
  ports:
    - port: 80
      name: http
  clusterIP: None
  selector:
    app: sassational-nginx
