apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-nginx
  labels:
    app: sassational-ginx
spec:
  selector:
      app: sassational-nginx
  ports:
    - port: 80
      name: http
      targetPort: 80
  type: ClusterIP
